### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by 1268** [lf-/clipper#9]
is Windows explicitly not supported? is support planned?

**Comment by lf-** [comment]
See the README. Windows is not supported and I am not writing/able to write Windows support since I don't have a Windows computer.

If you wanted to implement Windows support, I would suggest first figuring out how to get `clipper_inject` working on Windows and possibly the associated build engineering/CI. Frida GUM works on Windows, but you'd have to probably figure out how programs usually ship their TLS support on Windows, since I doubt it's usually openssl. I am currently investigating how to write tests for the key extraction parts, and those would be a prerequisite for merging any kind of Windows support.

**Comment by 1268** [comment]
> how programs usually ship their TLS support on Windows, since I doubt it's usually openssl.

Its not. OpenSSL is available as a native Windows library, but a more typical solution is something like Schannel, since its pre installed:

https://everything.curl.dev/build/tls

**Comment by lf-** [comment]
Ah, yeah. Ok. Here's some brief research into that:

- Quic: MsQuic supports it: https://github.com/microsoft/msquic/blob/main/docs/Settings.md#connection-parameters. Clipper does not currently support QUIC.
- S/Channel: You're screwed (have to tamper with LSASS, which is *extremely* intrusive and I probably wouldn't accept such a patch), and it may *additionally* be protected by Credential Guard. I don't see any way this could be made into a nice user experience.
  - https://social.technet.microsoft.com/Forums/en-US/4041d78a-21bb-44fd-9a96-6579ea8129d1/obtaining-sslkeylogfilelike-data-from-edge-et-al-schannel-clients?forum=messageanalyzer
  - https://github.com/dotnet/runtime/issues/37915
  - https://b.poc.fun/decrypting-schannel-tls-part-1/
  - 



I think that based on this information, Windows support is quite possibly a waste of time no matter how much free time one might have to develop it (which, to be fair, is because of a kind of nice security architecture, but it screws us over).

**Comment by 1268** [comment]
yeah that doesn't seem like fun. Currently I am using MitmProxy which works fine, but it involves ceremony with any program you use it with:

~~~
curl `
--proxy 127.0.0.1:8080 `
--cacert C:/users/steven/.mitmproxy/mitmproxy-ca.pem `
https://example.com
~~~
